language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
  - sudo curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - poetry --version
# command to install dependencies
install:
  - poetry install
# command to run tests
script:
  - make lint