language: python
python: "3.6"

before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - export PATH=$PATH:$HOME/.poetry/bin

# command to install dependencies
install: make

# command to run tests
script:
  - make lint